name = "dotf-install"
compatibility_date = "2025-08-17"
pages_build_output_dir = "public"

[env.production]
compatibility_date = "2025-08-17"

[[env.production.pages_functions]]
directory = "functions"
